#!/bin/bash
#
# Setup Cron Jobs for Conductor Status Updates
#
# This script configures cron jobs for the conductor to send proactive
# status updates at configurable intervals.
#
# Environment Variables:
#   STATUS_UPDATE_SCHEDULE - Cron schedule expression (default: "0 */6 * * *" = every 6 hours)
#   STATUS_UPDATE_ENABLED - Set to "true" to enable (default: false)
#
# Usage:
#   setup-cron.sh              # Set up cron with default schedule
#   setup-cron.sh "*/30 * * * *"  # Custom schedule (every 30 minutes)
#   setup-cron.sh disable      # Disable cron updates

set -euo pipefail

CRON_USER="${USER:-user}"
CRON_FILE="/tmp/conductor-cron"
DEFAULT_SCHEDULE="0 */6 * * *"  # Every 6 hours at :00
LOG_FILE="/var/log/conductor-cron/setup.log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Check if cron updates are enabled
if [[ "${STATUS_UPDATE_ENABLED:-false}" != "true" ]] && [[ "${1:-}" != "force" ]]; then
    log "Status updates disabled (STATUS_UPDATE_ENABLED != true)"
    log "To enable, set STATUS_UPDATE_ENABLED=true or run: setup-cron.sh force"
    exit 0
fi

# Get schedule
SCHEDULE="${1:-${STATUS_UPDATE_SCHEDULE:-$DEFAULT_SCHEDULE}}"

if [[ "$SCHEDULE" == "disable" ]]; then
    log "Disabling cron status updates"
    crontab -r 2>/dev/null || true
    log "Cron jobs removed"
    exit 0
fi

log "Setting up cron jobs for status updates"
log "Schedule: $SCHEDULE"

# Validate cron schedule (basic check)
if ! echo "$SCHEDULE" | grep -qE '^[0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+'; then
    log "ERROR: Invalid cron schedule format: $SCHEDULE"
    log "Expected format: '* * * * *' (minute hour day month weekday)"
    exit 1
fi

# Create cron job entry
cat > "$CRON_FILE" <<EOF
# Conductor Status Update Cron Jobs
# Generated by setup-cron.sh at $(date '+%Y-%m-%d %H:%M:%S %Z')
#
# Schedule: $SCHEDULE

# Load environment variables from /etc/environment if exists
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Status update job
$SCHEDULE /usr/local/bin/status-update.sh >> /var/log/conductor-cron/status-update.log 2>&1

# Cron log rotation (weekly)
0 0 * * 0 find /var/log/conductor-cron -name "*.log" -mtime +7 -exec rm {} \; 2>/dev/null

EOF

# Install cron job
if crontab -l > /dev/null 2>&1; then
    log "Existing crontab found, backing up to /tmp/crontab.backup"
    crontab -l > /tmp/crontab.backup
fi

crontab "$CRON_FILE"
rm "$CRON_FILE"

log "✓ Cron jobs installed successfully"
log "Current crontab:"
crontab -l | tee -a "$LOG_FILE"

# Start cron service if not running
if command -v service >/dev/null 2>&1; then
    if ! pgrep cron >/dev/null 2>&1; then
        log "Starting cron service..."
        sudo service cron start || log "WARNING: Could not start cron service (may need root)"
    else
        log "Cron service already running"
    fi
fi

log "Setup complete"
log ""
log "To modify schedule, run: setup-cron.sh 'NEW_SCHEDULE'"
log "To disable updates, run: setup-cron.sh disable"
log ""
log "Examples:"
log "  Every hour:        setup-cron.sh '0 * * * *'"
log "  Every 30 minutes:  setup-cron.sh '*/30 * * * *'"
log "  Twice daily:       setup-cron.sh '0 9,21 * * *'"
log "  Daily at 3am:      setup-cron.sh '0 3 * * *'"
